### PR TITLE
Revert "Mark dead service as unhaelthy"

### PR DESCRIPTION
**Pull request by janisz**
Reverts dcos/dcos-diagnostics#202 for some reason this change prevent DC/OS tests to start https://github.com/dcos/dcos/pull/7681

### CODE REVIEW

**Comment by vinodkone** [comment]
when you say "DC/OS tests" do you mean some integration tests or something that'll break in production? do you know what the error is?

**Comment by janisz** [comment]
@vinodkone All terraform tests failed see bump PR https://github.com/dcos/dcos/pull/7681

**Comment by janisz** [comment]
In logs it looks like dcos-diagnostics could not start 
```
dcos-diagnostics[12461]: time="2020-09-30T12:37:40Z" level=warning msg="Get \"https://127.0.0.1:443/exhibitor/exhibitor/v1/cluster/status\": dial tcp 127.0.0.1:443: connect: connection refused"
```

**Comment by vinodkone** [comment]
Hmm. The error you posted looks like a connection refused error from exhibitor? What do exhibitor logs say? Do you want to invest time into RCA or just revert it?

**Comment by janisz** [comment]
IMO we should merge it

**Comment by janisz** [comment]
Nobody merged it over a week so I think it's fair to close

**Pull request closed without merging**
