### PR TITLE
Return 200 when deleting already deleted bundle

### PR DESCRIPTION
**Pull request by janisz**
Fixes: https://jira.mesosphere.com/browse/DCOS-58105

### CODE REVIEW

**Comment by janisz** [comment]
What endpoint? Get alwyas returns bundle status even when it's `DELETED`. When bundle is deleted you can't get it's file, it returns 404 https://github.com/dcos/dcos-diagnostics/blob/df3a67a0658d103d55bfd734d86ae818aeeb2e30/api/rest/bundle_handler_test.go#L722-L723

**Comment by janisz** [comment]
@bamarni I think I know what you mean (the ticket has a typo 304 instead of 404). I fixed the code so now when bundle was deleted/failed/canceled we returns 410 instead of 404.

**Comment by bamarni** [comment]
@janisz : It's not a typo, I was referring to https://github.com/dcos/dcos-core-cli/blob/90e03f6af36aac507e73657abf59542ad3f745b7/pkg/diagnostics/v2/client.go#L139, the client seems to expect a 304 here. But I didn't check if the API can actually return a 304, maybe it's a mistake in the client?

**Comment by janisz** [comment]
Is now ok or should I change anything? There are two separate endpoints one to get bundle status and second to download file

**Comment by bamarni** [comment]
@janisz : should be good, browsing through the code it seems like the line I've linked is an inconsistency in the client only.

**Pull request merged**
