### PR TITLE
Convert vendor folder to godep and update all packages 

### PR DESCRIPTION
**Pull request by janisz**
*    remove vendor folder from govendor
*   use godep
*    bump all packages to the latest version
*    replace github.com/Sirupsen/logrus with github.com/sirupsen/logrus

### CODE REVIEW

**Comment by janisz** [comment]
Rebased #36

**Comment by janisz** [comment]
@klueska @philipnrmn Can you take a look?

**Comment by philipnrmn** [comment]
Hi @janisz , looks like we deleted `runner/checks.go` in the last commit. What's going on there?

**Comment by janisz** [comment]
@philipnrmn It was my fault. I rebased it improperly. Can you review it one more time?

**Pull request merged**
